using SF2MusicCooker.Furnace;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Text;

namespace SF2MusicCooker
{
    public static class AsmSheetWriter
    {
        const string padding = "\t\t";

        private static readonly byte[] supportedEffects = new byte[]
        {
            Effect.GoTo, Effect.GoNext, Effect.End, Effect.Pan, Effect.PanTrinary
        };

        /// <summary>
        /// Get the optimal "Timer B" value to play the song at the intended rate.
        /// </summary>
        public static byte GetOptimalTimerB(float targetPlaybackRate)
        {
            // Timer frequency (hz) = 1.0 / [ (256 - value) * 0.00030034 ]
            // Vanilla SF2 songs tend to have a value of 200 (C8) => that gives 59.46 hz

            // Yeah, I was too lazy to solve it with algebra xD
            float lowestError = float.PositiveInfinity;
            int bestValue = 0;

            for (int value = 0; value <= 255; value++)
            {
                float playbackRate = 1.0f / ((256 - value) * 0.00030034f);
                float error = Math.Abs(targetPlaybackRate - playbackRate);

                if (error < lowestError)
                {
                    bestValue = value;
                    lowestError = error;
                }
            }
            return (byte)bestValue;
        }

        /// <summary>
        /// Print the list of unsupported effects in the given Furnace file.
        /// </summary>
        public static void PrintUnsupportedEffects(FurnaceFile file)
        {
            HashSet<byte> set = file.GetAllEffectTypes();
            set.ExceptWith(supportedEffects);
            if (set.Count > 0)
            {
                StringBuilder sb = new StringBuilder(set.Count * 5);

                foreach (byte type in set)
                {
                    if (sb.Length > 0) sb.Append(" ");
                    sb.Append(Tools.Hex1(type));
                    sb.Append("..");
                }

                Console.WriteLine("! The song contains {0} unsupported effect{1}:", set.Count, set.Count > 1 ? "s": "");
                Console.WriteLine("    " + sb);
            }
        }

        /// <summary>
        /// Verify that all sample notes play their samples at C-4 otherwise print a warning.
        /// </summary>
        public static void PrintUnsupportedSampleMaps(Instrument[] usedInstruments)
        {
            int index = 0;
            foreach (Instrument instrument in usedInstruments)
            {
                if (instrument.Type == Instrument.DAC)
                {
                    SampleMap sampleMap = FeatureInterpreter.ParseFurnaceSampleInstrument(instrument.Data);
                    SampleMap.Entry[] pitchShiftedEntries = sampleMap.PitchShiftedEntries;

                    if (pitchShiftedEntries.Length > 0)
                    {
                        Console.WriteLine("! The song contains sample map instrument #{0} with pitch-shifted samples (i.e: not played at C-4 rate)", index);
                        Console.WriteLine("  Pitch-shifted samples are unsupported; end result will sound incorrect if you proceed without adjusting sample map");

                        // NOTE: we could silently fix this for the user by duplicating the sample with the pitch-shifted rate and changing the map to point to this new sample at C-4 rate
                        // But I think if you compose a Furnace track for the Sega Genesis you are probably not gonna pitch-shift your samples anyway
                    }
                }
                index++;
            }
        }

        /// <summary>
        /// Outputs an ASM music sheet.
        /// </summary>
        public static string Write(FurnaceFile file, Options options, InstrumentMap map, PitchTable pitch, int number, int pairNumber = 0)
        {
            StringBuilder sb = new StringBuilder(1024);
            Stopwatch sw = Stopwatch.StartNew();

            // Configuration for music
            ChannelCommands channels = new ChannelCommands(10, ChannelCommands.Mask_Music, false, Environment.NewLine + padding);

            // Generate the channels
            channels.Generate(file, options, map, pitch);

            // YM timer B (song tempo)
            byte timer = GetOptimalTimerB(file.PlaybackRate);

            // Write disclaimer
            sb.AppendFormat("; Generated by {0}", Tools.GetAssemblyNameAndVersion()); sb.AppendLine();
            sb.AppendFormat("; This output is from an automated tool, please avoid manual edits in it, instead it is better to improve/fix the tool!"); sb.AppendLine();
            sb.AppendLine();

            // Write header
            sb.AppendFormat("Music_{0}:", number);
            if (options.Title != null) sb.AppendFormat("\t\t; {0}", options.Title);
            sb.AppendLine();
            if (pairNumber > 0) { sb.AppendFormat("Music_{0}:\t\t; Special case, these two musics are paired", pairNumber); sb.AppendLine(); }
            sb.AppendFormat(padding + "db 0\t; Must be zero"); sb.AppendLine();
            sb.AppendFormat(padding + "db {0}\t; DAC mode (0=YES, 1=NO)", channels.DAC); sb.AppendLine();
            sb.AppendFormat(padding + "db 0\t; Reserved"); sb.AppendLine();
            sb.AppendFormat(padding + "db {0}\t; YM Timer B (music tempo)", Tools.Hex1ASM(timer)); sb.AppendLine();

            // Write channels
            channels.Write(sb, "Music_" + number, padding);

            // We have generated the full ASM to describe the music!
            string asm = sb.ToString();

            // Count number of bytes it will take in bank and show it on first line as a comment
            asm = "; MUSIC SIZE = " + AsmSheetToolkit.EstimateBytes(asm) + " (approximately)" + Environment.NewLine + asm;

            // Additional emptiness remark
            if (channels.Empty) asm = "; This is an empty music and it won't produce any sound output" + Environment.NewLine + Environment.NewLine + asm;

            // Print how much time it took
            if (!channels.Empty) Console.WriteLine("> Building ASM sheet took {0} ms", sw.ElapsedMilliseconds);

            // All done!
            return asm;
        }

        /// <summary>
        /// Outputs an ASM SFX sheet.
        /// </summary>
        public static string WriteSFX(SFXType type, FurnaceFile file, Options options, InstrumentMap map, PitchTable pitch, int number)
        {
            StringBuilder sb = new StringBuilder(1024);
            Stopwatch sw = Stopwatch.StartNew();

            // Configuration for SFX
            uint mask = type == SFXType.Type1_PSG_Square3_Noise ? ChannelCommands.Mask_SFX_1 : ChannelCommands.Mask_SFX_2;
            ChannelCommands channels = new ChannelCommands(10, mask, type == SFXType.Type2_YM_Ch4_Ch5_Ch6DAC, Environment.NewLine + padding);

            // Generate the channels
            channels.Generate(file, options, map, pitch);

            // Write header (disclaimer is skipped for SFX)
            sb.AppendFormat("Sfx_{0}:", number);
            if (options.Title != null) sb.AppendFormat("\t\t; {0}", options.Title);
            sb.AppendLine();
            sb.AppendFormat(padding + "db {0}\t; SFX type", (byte)type); sb.AppendLine();

            // Write channels
            channels.Write(sb, "Sfx_" + number, padding);

            // We have generated the full ASM to describe the SFX!
            string asm = sb.ToString();

            // Print how much time it took
            if (!channels.Empty) Console.WriteLine("> Building ASM sheet took {0} ms", sw.ElapsedMilliseconds);

            // All done!
            return asm;
        }
    }
}